### PR TITLE
Delay Plater mod setup until after TRP3 is loaded

### LINKED ISSUE #1280: TRP3 Plater Nameplates Initialization Error
This issue was reported to Plater under the assumption it was triggered by Plater and was since been noted that it is related to TRP3 and not their end.

## Describe the issue
Upon logging in with Plater Nameplates module enabled and Plater enabled, an initialization error triggers.
Nameplates appear to be functioning as intended despite the error.

## Expected behaviour
Initialize as intended or fail gracefully.

## Issue checklist
Please select any applicable options from the below list.

- [x] The issue occurs with the [latest version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [x] The issue occurs only with other addon(s) enabled (please provide a list).
- Plater Nameplates

## Steps to reproduce
1. Enable TRP3
2. Enable Plater Nameplates Module
3. Enable Plater
4. Login/Reload

## Additional files
Image

### PR DESCRIPTION
**Pull request by Ghostopheles**
Fixes #1280 

Updates the included Plater mod used by the nameplates module to defer setup until after TRP3 is loaded.

Honestly, not even sure how this worked to begin with. Probably some obscure change in some hard-to-reach place - but regardless, local Plater users can rejoice.

Since we can't diff the actual code change in the mod itself, I'll include it here for our local historian and/or loremaster.

```diff
function (modTable)
    if not C_AddOns.IsAddOnLoaded("TotalRP3") then
        return false
    end

-    modTable.interface = TRP3_PlaterNamePlates:RegisterModTable(modTable)
-    return true
+    if not TRP3_PlaterNamePlates then
+        EventUtil.ContinueOnAddOnLoaded("TotalRP3", function()
+                modTable.interface = TRP3_PlaterNamePlates:RegisterModTable(modTable);
+        end);
+    else
+        modTable.interface = TRP3_PlaterNamePlates:RegisterModTable(modTable)
+        return true
+    end
end
```

EDIT: We can now diff the Plater mod itself.

### CODE REVIEW

File: totalRP3/Modules/NamePlates/NamePlates_Plater.lua [hunk 1]
```diff
@@ -4,12 +4,132 @@
...
+		affix = {},
+		encounter_ids = {},
+		map_ids = {}
+	},
+	Hooks = CopyTable(platerHooks),
+	HooksTemp = {},
+	LastHookEdited = "",
+	url = "",
+	version = -1,
+	semver = ""
```
Comment (Meorawr) [inline totalRP3/Modules/NamePlates/NamePlates_Plater.lua]:
```suggestion
	semver = "",
```
At this point it's just embarassing.

**Review by Solanya — APPROVED** [review]
Surely it works yes
